### ISSUE TITLE
mlr_measures_classif.costs & predict_type = "prob": Change the prob threshold

### ISSUE THREAD

**Issue by andreassot10** [mlr-org/mlr3measures#14]
The cost-sensitive measure `mlr_measures_classif.costs` requires a 'response' predict type.

```
msr("classif.costs")
#<MeasureClassifCosts:classif.costs>
#* Packages: -
#* Range: [-Inf, Inf]
#* Minimize: TRUE
#* Properties: requires_task
#* Predict type: response
```
This measure seems to be working even when a learner's `predict_type` is set to 'prob':

```
# get a cost sensitive task
task = tsk("german_credit")

# cost matrix as given on the UCI page of the german credit data set
# https://archive.ics.uci.edu/ml/datasets/statlog+(german+credit+data)
costs = matrix(c(0, 5, 1, 0), nrow = 2)
dimnames(costs) = list(truth = task$class_names, predicted = task$class_names)
print(costs)

# mlr3 needs truth in columns, predictions in rows
costs = t(costs)

# create measure which calculates the absolute costs
m = msr("classif.costs", id = "german_credit_costs", costs = costs, normalize = FALSE)

# fit models and calculate costs
learner = lrn("classif.rpart", predict_type = "prob")
rr = resample(task, learner, rsmp("cv", folds = 3))
rr$aggregate(m)

#german_credit_costs 
#               341
```

Is this a bug or does the measure internally convert probabilities into classes? I guess the threshold for predicting a class as positive or negative is internally set to 0.5? Can one change this threshold?

**Comment by mllg** [comment]
> Is this a bug or does the measure internally convert probabilities into classes?

Yes, the probabilities are automatically converted to labels. The threshold can be controlled via threshold tuning which will be in the next mlr3pipelines version (@pfistfl is implementing it right now). 

Hope that helps.
