### ISSUE TITLE
Consider using {mathjaxr} for formula rendering in help pages

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3measures#26]
https://github.com/wviechtb/mathjaxr

**Comment by mllg** [comment]
Formulas are properly rendered in ASCII/html/pdf, I don't see why we need this.

**Comment by pat-s** [comment]
Wouldn't it be way nicer to render formulas via Mathjax instead of having ASCII representations of them? 

What do you mean by "properly rendered" in this case? Am I overlooking something?

**Comment by mllg** [comment]
Ah, I forgot about the local html help. PDF and pkgdown already render properly.

**Comment by pat-s** [comment]
And the local html help might actually be the most used one :)

**Comment by mllg** [comment]
AFAICT the RD macros are evaluated at build-time. We inherit the documentation in mlr3, so mlr3 would also need to import `mathjaxr`.

**Comment by mllg** [comment]
Next version of R will come with the katex js library, so I guess we won't need mathjax.
