### ISSUE TITLE
Element with key 'classif.mauc_aunu' not found in DictionaryMeasure!

### ISSUE THREAD

**Issue by aoandrade** [mlr-org/mlr3measures#35]
### Description

rr[[2]]$score(msr("classif.mauc_aunu"))  
Error: Element with key 'classif.mauc_aunu' not found in DictionaryMeasure!

### Reproducible example

rr[[2]]$score(msr("classif.mauc_aunu"))  
Error: Element with key 'classif.mauc_aunu' not found in DictionaryMeasure!

# All the measures below work, but not classif.mauc_aunu
rr[[2]]$score(msr("classif.acc")) # Classification Accuracy
rr[[2]]$score(msr("classif.bacc")) # Balanced Accuracy
rr[[2]]$score(msr("classif.ce")) # Classification Error
rr[[2]]$score(msr("classif.logloss"))  # logloss
rr[[2]]$score(msr("classif.mbrier"))

**Comment by mllg** [comment]
These measures are not yet supported by mlr3, but will be in the next release (see https://github.com/mlr-org/mlr3/pull/844).
