### ISSUE TITLE
Instance-wise loss

### ISSUE THREAD

**Issue by mnwright** [mlr-org/mlr3measures#39]
Many measure aggregate over instances, e.g. the weighted mean in MSE here: https://github.com/mlr-org/mlr3measures/blob/680a9b1fbb36926a57a1e0825f761bf6a3b8e531/R/regr_mse.R#L18

Could we have something like an `aggregate` argument (default `TRUE`) to return instance-wise loss instead of aggregated loss if set to `FALSE`? Would be useful e.g. for https://github.com/bips-hb/cpi/pull/13.

Happy to create a PR for this.

**Comment by jemus42** [comment]
There are now a handful of observation-wise losses available, but the only one that's missing for me now is an observation-wise version of `logloss`.

**Comment by mnwright** [comment]
Thanks! I would have liked the aggregate approach described above, but having additional per-observation losses does the trick. So I'll close here.

**Comment by jemus42** [comment]
We still don't have an approach to call e.g. instance-wise square loss by doing `msr("regr.mse", aggregated = FALSE)` or something and I don't know what the plan is, or what the API would be like.

Calling `$score()` on a prediction object but getting _not_ scores aggregated over the entire dataset would break existing conventions, so not sure how that would work 🤷🏻
