### ISSUE TITLE
Parameters in Measure objects

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3measures#5]
Hi, I couldn't see this answered in the book or in this GitHub but forgive me if it has been somewhere else. What's the correct way to include parameters in a Measure object? For example I can see that the logloss formula has a parameter for `eps`, but how yould you include this in `MeasureClassifLogloss` (which I can't find implemented)? Thanks

**Comment by RaphaelS1** [comment]
Is it okay to add these into the constructor similarly to this?
https://github.com/mlr-org/mlr3/blob/master/R/MeasureClassifCosts.R

**Comment by berndbischl** [comment]
> Is it okay to add these into the constructor similarly to this?

of course? you can subclass, add members and add them to the constructor? 
just because most standard measures do not have these extra-constants does not mean you are not allowed to do this in general. and with "cost-measure" you have picked a good example where this was already necessary

**Comment by RaphaelS1** [comment]
Great just wanted to make sure this didn't go against any measure design principles. Thanks !
