### ISSUE TITLE
Measures: Flexibility and extending to new task_types

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3measures#7]
Example: 
In `mlr3forecasting`, we could basically use `regr.mse` in order to score a forecast.

Currently, this is not allowed because `assert_measure` compares the task_type of measure and task.

I guess I could use a policy for how we want to solve such issues in general:
- Open up measure to more types? This would require a reflection mechanism.
- Re-add all applicable measures for the new type?

Additionally, in `measures.R` L. 20 I found the following assertion:
`type = assert_choice(type, c("binary", "classif", "regr"))`

I guess this does not extend naturally to other task types. 
Do we want to add measures from other packages to the measures dictionary?

**Comment by pfistfl** [comment]
@mllg : Would be cool if we could resolve this ASAP

**Comment by mllg** [comment]
> Additionally, in `measures.R` L. 20 I found the following assertion:
> `type = assert_choice(type, c("binary", "classif", "regr"))`

This is just an internal function and is not called outside the mlr3measures package.

**Comment by mllg** [comment]
> Currently, this is not allowed because `assert_measure` compares the task_type of measure and task.
> 
> I guess I could use a policy for how we want to solve such issues in general:
> 
>     * Open up measure to more types? This would require a reflection mechanism.
> 
>     * Re-add all applicable measures for the new type?

Unsure what to do here. Is there a special prediction object or do you return a PredictionRegr?

**Comment by berndbischl** [comment]
i think we are doing something maybe not too optimal here wrt to designing these checks. we also had this problem before in mlr3. can we not get rid of this strict type check somehow?

**Comment by berndbischl** [comment]
actually, i dont even think we can answer this right now. @pfistfl i think we can only make a decision how / if we should change this in mlr3 if we can understand how mlr3forecast is supposed to work. are there some specs one can read to understand how predictions are formed?

**Comment by pfistfl** [comment]
So I currently have no real specs, but assume a `PredictionForecast` has the following format:

```r
> learner$predict(tsk)
<PredictionForecast> for 144 observations:
    row_id truth.target response.target se.target
         1          112        483.3799  26.57699
         2          118        490.9993  40.04842
         3          132        520.2773  43.85939
---                                              
       142          461        857.9275  50.56199
       143          390        860.6083  50.58429
       144          432        863.2892  50.60658
```

I have no idea how to properly evaluate forecasting methods, but a  `mse` between predicted and truth does seem like a sensible first step.

In the multivariate case, predictions might either have two columns per `target` (response and se) or , 
we might as well save them in a long format. But I guess it would be a win for now if we can deal with the univariate case.

**Comment by mllg** [comment]
This is basically a `PredictionRegr` - could you use it directly?

Alternatively, I can turn off some assertions. Or allow multiple task types for Prediction objects (well, maybe then also find a better field name). @Coorsaa had a similar problem with mlr3ordinal ... IDK what his solution was in the end.

**Comment by pfistfl** [comment]
Well, we still have the multivariate case where things are not exactly the same (and where we would need to define a measure that works, perhaps average `mse` of the different targets? 

I am also unsure how we wanna handle this.

One idea that might work in the meantime is that I simple re-export every measure as a 
measure forecast similar to https://github.com/mlr-org/mlr3/blob/master/R/MeasureSimple.R,
i.e. loop over `regr` measures and re-export for forecast with a `.forecast` suffix.
Then people would use `msr("rmse.forecast")` and we'd have solved the problem for now.

**Comment by mllg** [comment]
Re-exporting is probably the cleanest solution.
